<a href="https://colab.research.google.com/github/yashpanchal089/Machine-Learning/blob/main/MLR_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pwd

'/content'

In [ ]:
from google.colab import files
uploaded = files.upload()
#importing data set file

Saving taxi.csv to taxi.csv


In [ ]:
data = pd.read_csv ('taxi.csv')# Loading data set
data.head(15)

Priceperweek  Population  ...  Averageparkingpermonth  Numberofweeklyriders
0             15     1800000  ...                      50                192000
1             15     1790000  ...                      50                190400
2             15     1780000  ...                      60                191200
3             25     1778000  ...                      60                177600
4             25     1750000  ...                      60                176800
5             25     1740000  ...                      70                178400
6             25     1725000  ...                      75                180800
7             30     1725000  ...                      75                175200
8             30     1720000  ...                      75                174400
9             30     1705000  ...                      80                173920
10            30     1710000  ...                      80                172800
11            40     1700000  ...                      80                163200
12            40     1695000  ...                      85                161600
13            40     1695000  ...                     100                161600
14            40     1690000  ...                     105                160800

[15 rows x 5 columns]

In [ ]:
len(data)

27

In [ ]:
data_x=data.iloc[:, 0:-1].values # select till the second last columnof the data frame(instead of the last column)
data_y= data.iloc[:,-1].values # gives values of the last column

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(data_x, data_y, test_size=0.3, random_state=42) # split the data in training and testing

In [ ]:
from sklearn.linear_model import LinearRegression # Apply linear model

In [ ]:
reg=LinearRegression()
reg.fit(x_train,y_train) #fit for train the model.training completed here.

LinearRegression()

In [ ]:
y_pred=reg.predict(x_test) # Show the predicted values
y_pred

array([174616.14046152, 169014.18298305, 173424.44493672, 138910.62549881,
       189468.43963632, 167889.32606295, 148484.79928331, 125839.98908894,
       168155.81815997])

In [ ]:
y_test # show the actual values

array([174400, 161600, 173920, 136000, 192000, 163200, 148800, 115696,
       161600])

In [ ]:
print(reg.coef_) #print coeficent values  i.e. b1,b2,b3 and b4

[-6.09975408e+02  1.15770862e-01  8.34663883e-01  4.22003717e+01]


In [ ]:
print(reg.intercept_)

-16720.55067685686
